sudo: false

os: linux

dist: trusty

python:
  - 3.6

language: python

cache:
  - pip

notifications:
  email: false

branches:
  only:
    - master

install:
  - pip install .
  - pip install flake8

script:
  - flake8 .
